export const FEAUTURE_NAME_METADATA = 'iscssoft_FEAUTURE_NAME_METADATA';
export const ACTION_NAME_METADATA = 'iscssoft_ACTION_NAME_METADATA';
export const OVERRIDE_METHOD_METADATA = 'iscssoft_OVERRIDE_METHOD_METADATA';
export const PARSED_BODY_METADATA = 'iscssoft_PARSED_BODY_METADATA';
export const PARSED_CRUD_REQUEST_KEY = 'iscssoft_PARSED_CRUD_REQUEST_KEY';
export const CRUD_OPTIONS_METADATA = 'iscssoft_CRUD_OPTIONS_METADATA';
export const CRUD_AUTH_OPTIONS_METADATA = 'iscssoft_CRUD_AUTH_OPTIONS_METADATA';
